#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Overall title for pages.
title: "Metadata Assessment"

# Contact email address.
email: cmharlow@gmail.com

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: cmh2166/CULMetadataAssessment

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
